/* Generated by tools/mkglobals.py -- do not hand-edit.
 *
 * Storage for the 826 globals the decompiled sources declare and no
 * translation unit defines. See the script for the pointer-slot rule.
 */

#include "gamecode_globals.h"

#define SLOT_WORDS 64

/* ---- 672 plain globals ---- */

long AIOn;  /* 0x0014e1f4 */
long AboutPage;  /* 0x00101190 */
char AboutSpiltText[SLOT_WORDS];  /* 0x0018dd5c, 256 bytes a line */
char AllFramesTable[SLOT_WORDS];  /* pointer slot -> 0x00218cc4 */
long AnimSmoothWindowSize;  /* 0x00171368 */
long AnimalityMessageCounter;  /* 0x0014fb38 */
long AnimalityMessageG;  /* 0x0014fb2c */
float AttachTransforms[SLOT_WORDS];  /* 0x0018ee00 */
float AverageFPS;  /* 0x0014e1d4 */
long AverageFPSCount;  /* 0x0014e1d0 */
int AxeTrailDisallowed;  /* 0x00150eac */
long BGRandomised;  /* 0x000ff8b4 */
long BGSceneController[SLOT_WORDS];  /* 0x001aba88, twelve bytes an entry */
float BGSceneFrame[2];  /* 0x001abb20 */
void *BGSceneHandle;  /* 0x001aba40 */
void *BGSceneHandle2;  /* 0x001aba44 */
long BGSceneLoops[2];  /* 0x001aba80 */
BUTTONNEW BUTTON_1X1_1D;  /* 0x0010053c */
BUTTONNEW BUTTON_1X2_1D;
BUTTONNEW BUTTON_1X2_2D;
BUTTONNEW BUTTON_1X3_1;  /* 0x001004d8 */
BUTTONNEW BUTTON_1X3_2;  /* 0x001004ec */
BUTTONNEW BUTTON_1X3_3;  /* 0x00100500 */
BUTTONNEW BUTTON_BACK;  /* 0x001007bc */
BUTTONNEW BUTTON_BOXLB;  /* 0x001004b0 */
BUTTONNEW BUTTON_BOXLT;  /* 0x00100488 */
BUTTONNEW BUTTON_BOXRB;  /* 0x001004c4 */
BUTTONNEW BUTTON_BOXRT;  /* 0x0010049c */
BUTTONNEW BUTTON_CANCEL;  /* 0x0010085c */
BUTTONNEW BUTTON_DEL;  /* 0x00100794 */
BUTTONNEW BUTTON_EXIT;  /* 0x00100834 */
BUTTONNEW BUTTON_EXITBIG;  /* 0x001007d0 */
BUTTONNEW BUTTON_MINI_1;  /* 0x00100550 */
BUTTONNEW BUTTON_MINI_2;  /* 0x00100564 */
BUTTONNEW BUTTON_MINI_3;  /* 0x00100578 */
BUTTONNEW BUTTON_MP_NEXT;  /* 0x00100870 */
BUTTONNEW BUTTON_MP_PREV;  /* 0x00100884 */
BUTTONNEW BUTTON_NEXT;  /* 0x0010080c */
BUTTONNEW BUTTON_NEXTSTATS;  /* 0x001007f8 */
BUTTONNEW BUTTON_OK;  /* 0x001007a8 */
BUTTONNEW BUTTON_PLAY;  /* 0x001007e4 */
BUTTONNEW BUTTON_PREV;  /* 0x00100820 */
BUTTONNEW BUTTON_SAVE;  /* 0x00100848 */
float BabalityHeight[8];  /* 0x001f4124 */
long BabalityMessageG;  /* 0x0014fb28 */
float BabalityVel[8];  /* 0x001f4104 */
long BioPage;  /* 0x0010107c */
char BioSplitText[SLOT_WORDS];  /* 0x00185d58, 256 bytes a line */
long BioText[BIOS_PAGES];  /* 0x00101014, -1 means no page */
float BlendMode;
float BloodGravity;  /* 0x0016f74c */
float BloodSize;  /* 0x0016f744 */
TEXTURETOLOAD BloodTexturesToLoad[SLOT_WORDS];  /* 0x00150e1c */
float BloodVelMul;  /* 0x0016f748 */
void *BricksTexture;  /* 0x00183efc */
long ButtonEditMode;  /* 0x00100f84 */
char ButtonSplitText[SLOT_WORDS];  /* 0x00184730, 256 bytes a line */
char ButtonSplitText2[SLOT_WORDS];  /* 0x00184f30 */
long ButtonStates[7];  /* 0x0014fef4 */
long ButtonStatesP2[7];  /* 0x0014ff2c */
long ButtonsPos[SLOT_WORDS];  /* 0x001f4144 */
long ButtonsPos4[SLOT_WORDS];  /* 0x0015012c */
long ButtonsPos5[SLOT_WORDS];  /* 0x001501a4 */
long ButtonsPos6[SLOT_WORDS];  /* 0x0015021c */
long ButtonsPos6P2_1[SLOT_WORDS];  /* 0x0015003c  2P six-button, player 1 */
long ButtonsPos6P2_2[SLOT_WORDS];  /* 0x001500b4  2P six-button, player 2 */
long ButtonsPosP2[SLOT_WORDS];  /* 0x001f41bc */
long ButtonsPosP2_1[SLOT_WORDS];  /* 0x0014ff4c  2P mode, player 1 */
long ButtonsPosP2_2[SLOT_WORDS];  /* 0x0014ffc4  2P mode, player 2 */
long CS_Layout[CS_ROWS][CS_COLS];  /* 0x00101630 */
long CS_Layout2[CS_ROWS][CS_COLS];  /* 0x001016a0 */
float CamLeftLimit;  /* 0x001f44a8 */
float CamLeftLimit3d;  /* 0x001f44b0, world units */
float CamOverridePos[3];  /* 0x001ab000 */
float CamRightLimit;  /* 0x001f44ac */
float CamRightLimit3d;  /* 0x001f44b4 */
float CamVelX;  /* 0x0014dfac */
float Camera[SLOT_WORDS];  /* pointer slot -> 0x0014fa74 */
char CancelCustomButtonsPos4[0x78];
char CancelCustomButtonsPos5[0x78];
char CancelCustomButtonsPos6[0x78];
void *CancelTexture;
long Character1;  /* 0x000ff988 */
int *Character1Ptr;  /* slot -> 0x000ff988 */
long Character2Override;  /* 0x00101798 */
signed char CharacterAvailable[CHARACTER_SLOTS];  /* 0x0018ed5c */
int CharacterConfirmed;  /* 0x000ff8cc */
int CharacterSelected;  /* 0x000ff8d0 */
void *CharacterVSTexture[26];  /* 0x00183d80 */
void *CharacterVSTexture2[26];  /* 0x00183de8 */
float Character_SelectWait;  /* 0x000ff8c8 -- a FLOAT. */
long ClassicSubZeroUnlocked;  /* 0x000ff970 */
int *ClassicSubZeroUnlockedPtr;  /* slot -> 0x000ff970 */
int ClearedZBuffer;  /* 0x001f44c8 */
void *CoinTPage;
GAMEFONT CountDownFont;  /* 0x001dbc50 */
CREDITSENTRY CreditsText[SLOT_WORDS];  /* 0x00101194 */
long CurrentScene;  /* 0x0014e29c */
int CurrentTask;  /* 0x00150590 */
char CustomButtonsPos4[0x78];  /* 0x00150294 */
char CustomButtonsPos5[0x78];  /* 0x0015030c */
char CustomButtonsPos6[0x78];  /* 0x00150384 */
char DEFAULT_CustomButtonsPos4[0x78];  /* 0x001503fc */
char DEFAULT_CustomButtonsPos5[0x78];  /* 0x00150474 */
char DEFAULT_CustomButtonsPos6[0x78];  /* 0x001504ec */
void *DangerTPage;
const char *DestinationGrandMaster[SLOT_WORDS];  /* 0x00176bd8 */
const char *DestinationMaster[SLOT_WORDS];  /* 0x00176b20 */
const char *DestinationNovice[SLOT_WORDS];  /* 0x001769f0 */
const char *DestinationWarrior[SLOT_WORDS];  /* 0x00176a80 */
const char **DestinyNamesLoss;
long DestinyToSelect;  /* 0x0010175c */
long DidIntroThisFrame;  /* 0x0010dec4 */
long DifficultyList[SLOT_WORDS];  /* 0x0014fc00, eleven words a row */
float DisplayAverageFPS;  /* 0x0014e1d8 */
long DisplaySurvivalStage;  /* 0x000ff984 */
float DistInX;  /* 0x001f44b8 */
long DoIntro;  /* 0x0014e1c0 */
long DoIntroFlag;  /* 0x0014e1c0 */
long DoSmokeEarthFatalSFX;  /* 0x0010df00 */
float DoSmokesEarthFatal;  /* 0x0010defc -- a TICK COUNTER, not a */
float DoingStageFatalBringForward;  /* 0x0010dee4 -- a float; Task_GameMain */
long DoneSmashEffect;  /* 0x0010ded4 */
long DontQuitAfterFade;  /* 0x0014e254 */
long DraggingButton;  /* 0x00100f80 */
int DrawRandomKode;  /* 0x001f44cc */
long DrawSpear[2];  /* 0x0010deec */
EDITVAR EditVars[SLOT_WORDS];  /* 0x00297970 */
long EndingWrapDone;  /* 0x00101158 */
long EndingsGained[23];  /* 0x00101088 */
long EndingsPage;  /* 0x0010114c */
char EndingsSplitText[SLOT_WORDS];  /* 0x00189d58, 256 bytes a line */
long EnduranceMatchTable2[SLOT_WORDS];  /* 0x00145f1c, two words a row */
long EnduranceMatchTreasure7[SLOT_WORDS];  /* 0x00145f3c, four words a row */
long EnduranceMatchTreasure8[SLOT_WORDS];  /* 0x00145f7c, four words a row */
int ErmacUnlocked;  /* 0x000ff974 */
int *ErmacUnlockedPtr;  /* slot -> 0x000ff974 */
long ExtraEffects;  /* 0x0014e1e8 */
float FECAMPOSX;  /* 0x00101710 */
float FECAMPOSY;  /* 0x00101714 */
float FECAMPOSZ;  /* 0x00101718 */
float FECamPos[3];  /* 0x000ff954 */
long FEChars[2];  /* 0x0018ed78 */
int FEInitState;  /* 0x001017a8 */
void *FENew1Texture;  /* 0x00183d7c */
float FEObjPos[3];  /* 0x000ff948 */
float FEPlayer1Offset;  /* 0x00183d68 */
float FEPlayer2Offset;  /* 0x00183d64 */
long FESlideDir;  /* 0x000ff848, -1 / 0 / 1 */
long FESlideNextTask;  /* 0x000ff84c */
float FESlideOffset;  /* 0x000ff844 */
const char *FETaskNames[SLOT_WORDS];  /* 0x00100d60 */
long FETuneSelection;  /* 0x000ff8f4 */
float FE_AspectRatioAdjust;  /* 0x000ff9c0 */
int FE_CurrentTask;  /* 0x001008bc */
int FE_CurrentTaskStack[SLOT_WORDS];  /* 0x00183f30 */
float FE_Fade;  /* 0x00100898 */
float FE_FadeAdd;  /* 0x0010089c */
float FE_HeightScale;  /* 0x000ff9bc */
int FE_LoadCount;  /* 0x001017ac */
int FE_TaskStackPointer;  /* 0x001008ac */
float FE_WidthScale;  /* 0x000ff9b8 */
float FE_YOffset;  /* 0x000ff9b4 */
long FadeMusicOut;  /* 0x0010dee8 */
long FatalityMessageCounter;  /* 0x0014fb3c */
long FatalityMessageG;  /* 0x0014fb30 */
float FightMessageTimer;  /* 0x0014e25c */
void *Fight_MeshAndTexture;  /* 0x00174eec */
void *Finishher_MeshAndTexture;  /* 0x00174ff4 */
void *Finishim_MeshAndTexture;  /* 0x001750fc */
void *FireLogo[10];  /* 0x00183e54 */
float FlawlessCounter;  /* 0x0014fb48 */
long FlawlessMessage;  /* 0x0014fb4c */
void *FloorTexture;  /* 0x00183ef8 */
MKMOVE FourButtonMoves[SLOT_WORDS];  /* 0x0015092c */
float FrameCompensation;  /* 0x0014e1f0 */
float FrameCompensationFE;  /* 0x000ff82c */
float FrameCount;  /* 0x0014fa60 */
void (*FrameID_GetBBoxPtr[SLOT_WORDS])(void);
long FrameInfo[SLOT_WORDS][4];  /* 0x0010df1c, the fallback */
long FrameInfo2[SLOT_WORDS][4];  /* 0x00129f1c, {x, y, w, h} */
long FriendshipMessageG;  /* 0x0014fb34 */
GAMESTATE *G;  /* 0x0038c1fc */
long GI_LoadCount;  /* 0x00151088 */
GAMEEVENT GameEvents[GAME_EVENT_SLOTS];  /* 0x00370e18 */
long GameInitState;  /* 0x00150e84 */
void *GameOverBottomTexture;  /* 0x00183f08 */
void *GameOverTopTexture;  /* 0x00183f04 */
int GameStarted;  /* 0x0014e208 */
float GameTime;  /* 0x0014fa58 */
long Generic_Moves5[SLOT_WORDS];  /* 0x001030d8 */
long Generic_Moves6[SLOT_WORDS];  /* 0x00103518 */
float GlassWindowPos[3];  /* 0x0014f9e4 */
void *HSceneTextures;  /* 0x006bc0a0 */
TEXTURETOLOAD HUDANIM_ttl[SLOT_WORDS];  /* 0x00174e4c */
void *HUDFatalsTexture[10];
void *HUDTPage;
float HUD_Scale;  /* 0x000ff9c4 */
long HelpPage;  /* 0x000ff840 */
char HelpSpiltText[SLOT_WORDS];  /* 0x00182c84, 256 bytes a line */
long *IdlesPerPlayer[SLOT_WORDS];  /* 0x00171288, {value, list} pairs */
long InGame;  /* 0x0010dec0 */
float InfoScale;  /* 0x0010de80 */
float InfoScaleAdd;  /* 0x0010de7c */
void *InfoTexture;
long InitGroundOffset;  /* 0x0014df90 */
float IntroAt[3];  /* 0x001abb74 */
long IntroCamCount;  /* 0x0014f940 */
float IntroCount;  /* 0x0014e1c4 */
float IntroCount2;  /* 0x0014e1c8 */
float IntroCountTimer;  /* 0x0014e1cc */
float IntroEye[3];  /* 0x001abb80 */
long IntroFrame1;  /* 0x0014f908 */
long IntroFrame2;  /* 0x0014f90c */
float IntroFrameComp;  /* 0x00151068 */
long **IntroLists;  /* 0x0014e008 */
float IntroLook[4][3];  /* 0x0014f974 */
float IntroPlayer1PosX;  /* 0x0014f930 */
float IntroPlayer1PosZ;  /* 0x0014f934 */
float IntroPlayer2PosX;  /* 0x0014f938 */
float IntroPlayer2PosZ;  /* 0x0014f93c */
float IntroPos[4][3];  /* 0x0014f944, 0x30 bytes exactly */
long IsEndurance;  /* 0x0014fcb0 */
float JINNERDIAL;  /* 0x00150594, read only here */
float JOUTERDIAL;  /* 0x00150598 */
float JSIZE;  /* 0x0014e1dc = 64.0 */
int JadeUnlocked;  /* 0x000ff97c */
int *JadeUnlockedPtr;  /* slot -> 0x000ff97c */
long JaxBeingSquashed;  /* 0x0010dedc */
int JaxGrowCounter;  /* 0x0010ded8 */
long JaxSquashFlip;  /* 0x001ab030 */
char JaxSquashedPlayer[SLOT_WORDS];  /* 0x001ab034 */
long JoyOffset[JOY_DIRECTIONS][2];  /* 0x000de09c, pixels, not scaled */
long JoystickState;  /* 0x0014febc */
long JoystickStateP2;  /* 0x0014fecc */
long JoystickStatePosX;  /* 0x0014fec0 */
long JoystickStatePosXP2;  /* 0x0014fed0 */
long JoystickStatePosXv;  /* 0x0014fec0 */
long JoystickStatePosY;  /* 0x0014fec4 */
long JoystickStatePosYP2;  /* 0x0014fed4 */
long JoystickStatePosYv;  /* 0x0014fec4 */
long JustWon;  /* 0x000ff9b0 */
long KodeEntered;  /* 0x000ff820 */
int KodeSelector[10];  /* 0x000ff8f8 */
float KodeSelectorParticle[10];  /* 0x000ff920 -- FLOATS. FE_Task_Treasure */
int KodeSuccess;  /* 0x000ff968 */
float KodeTime;  /* 0x000ff964 */
void *KodesTexture;  /* 0x00183f1c */
float KontinueTime;  /* 0x000ff960 */
long LIME_Paused;  /* 0x0014e004 */
char Language[10];  /* 0x001ab980 */
char *LanguageTextData;  /* 0x003857dc */
char **LanguageTextPtrs;  /* 0x003857d8, one pointer per string */
float LastAt[3];  /* 0x001f4448 */
long LastButtonPosX;  /* 0x00185d50 */
long LastButtonPosY;  /* 0x00185d54 */
long LastButtonStates[7];  /* 0x0014fed8 */
long LastButtonStatesP2[7];  /* 0x0014ff10 */
long LastDraggingButton;  /* 0x00100f7c */
long LastEnduranceCharacter;  /* 0x001ab674 */
float LastEye[3];  /* 0x001f4454 */
void *LastGObj;  /* 0x00150eb0 */
long LastJoyBitsIn;  /* 0x00150cc0 */
long LastSpecialButton[2];  /* 0x00150e98 */
long LastTouch_About1;
long LastTouch_About2;
long LastTouch_About3;
long LastTouch_About4;
long LastTouch_About5;
long LastTouch_About6;
long LastTouch_Extras1;
long LastTouch_Extras2;
long LastTouch_Extras3;
long LastTouch_Extras4;
long LastTouch_Extras5;
long LastTouch_Extras6;
long LastTouch_Options1;  /* 0x00100ed0 */
long LastTouch_Options2;  /* 0x00100ed4 */
long LastTouch_Options3;  /* 0x00100ed8 */
long LastTouch_Pause1;
long LastTouch_Pause2;
long LastTouch_Pause3;
long LastTouch_Pause4;
long LastTouch_Pause5;
long LastTouch_Pause6;
long LastTouch_PlayArcade;  /* 0x00100e70 */
long LastTouch_PlayMultiPlayer;  /* 0x00100e74 */
long LastTouch_PlaySK;  /* 0x00100e7c */
long LastTouch_PlaySurvival;  /* 0x00100e78 */
float LevelBGPos[3];  /* 0x0015057c */
void *LevelBGTexture[SLOT_WORDS];  /* 0x001abb28 */
long LevelMusic[SLOT_WORDS];  /* 0x0014f8c8 */
char Level_Info[SLOT_WORDS];  /* 0x0014e8d4 */
void *LightningTexture;  /* 0x00183e84 */
int LoadedBGExtents;  /* 0x0015108c */
TEXTURE *LoadingTexture;  /* 0x001abb94 */
char MPVersusSplitText[SLOT_WORDS];  /* 0x00185950, 256 bytes a line */
float M_Rot90[16];  /* 0x0018edc0 */
void *MainLogoTexture;  /* 0x00183f20 */
void *MainMenuBGTexture;  /* 0x00183f00 */
float MaxDistInX;  /* 0x00150e94 */
char Menu_GamePaused_Options[SLOT_WORDS];  /* 0x00150eb8 */
int Menu_Task_About_Eula[SLOT_WORDS];
int Menu_Task_About_Privacy_Policy[SLOT_WORDS];
int Menu_Task_About_Terms_of_Service[SLOT_WORDS];
int Menu_Task_Challenge[SLOT_WORDS];  /* 0x00100f18 */
int Menu_Task_Credits[SLOT_WORDS];
int Menu_Task_Game_Over[SLOT_WORDS];  /* 0x00101770 */
int Menu_Task_Get_More_Games[SLOT_WORDS];
int Menu_Task_Leaderboards[SLOT_WORDS];  /* 0x00100fa0 */
int Menu_Task_Lobby[SLOT_WORDS];
int Menu_Task_Manage_Profile[SLOT_WORDS];
long Menu_Task_Multiplayer[SLOT_WORDS];  /* 0x00100e94 */
int Menu_Task_Rematch[SLOT_WORDS];
int Menu_Task_Training[SLOT_WORDS];  /* 0x00100ec0 */
int Menu_Task_Wifi_Bluetooth[SLOT_WORDS];
float MercyMessageCounter;  /* 0x0014fb44 */
void **MeshSetLayers[8];  /* 0x0014f910 -- each entry points AT */
void *MeshSet_FLOOR;
void *MeshSet_LEVEL_01;  /* 0x001aba24 */
void *MeshSet_LIGHTNING1;
void *MeshSet_LIGHTNING2;
void *MeshSet_LIGHTNING3;
void *MeshSet_LIGHTNING4;
void *MeshSet_LIGHTNING5;
void *MeshSet_OPPONENTFACE;
void *MeshSet_PLAYERFACE;
void *MeshSet_SINGLEBRICK;
void *MeshSet_SPIRAL;
void *MeshSet_VORTEX1;
void *MeshSet_VORTEX2;
void *MeshSet_VORTEX3;
void *MeshSet_VORTEX4;
void *MeshSet_VORTEX5;
void *MeshSet_VS_BRICK;
void *MetalScreenTexture;  /* 0x00183f0c */
long MileenaUnlocked;  /* 0x000ff978 */
int *MileenaUnlockedPtr;  /* slot -> 0x000ff978 */
void *MoveIconsTexture;  /* 0x001abb70 */
long MoveListPage;  /* 0x00150eb4 */
float MoveUpTower;  /* 0x00101758 */
MOVESLISTENTRY MovesListTab[SLOT_WORDS];  /* 0x0010d918, thirteen words each */
float MusicVol[SLOT_WORDS];  /* 0x000ff830 -- an ARRAY, same correction: */
GAMEFONT NameFont;  /* 0x001c3bf4 */
void *NewBlackBloodTexture;
void *NewBloodTexture;  /* 0x001f4490 */
long NewCam;  /* 0x0014e1bc */
float NewCamera[3];  /* 0x0014fa8c */
float NewCameraLookAt[3];  /* 0x0014fa98 */
void *NewGreenBloodTexture;  /* 0x001f4494 */
long NumOfEndingsLines;  /* 0x0010115c */
int NumPreloadedCharacters;  /* 0x00171358 */
void *OrangeTexture;  /* 0x00183e50 */
ANIMATEDCHARACTER *OrigLoadedPlayers[2];  /* 0x00295ccc */
int OverrideCamera;  /* 0x0010dea8 */
float PGrav;  /* 0x0016f764 -- negative in the data */
long PIrand_seed;  /* 0x0016f740 */
float PScale[3];  /* 0x0016f768 */
float PSize;  /* 0x0016f774 */
PARTICLE Particles[PARTICLE_COUNT];  /* 0x001f44d4 */
void *PauseBGTexture;
long PauseMenuAreYouSure;  /* 0x0014e260 */
void *PauseTexture;
int PendingPop;  /* 0x001008b4, -1 when idle */
int PendingPopAll;  /* 0x001008b8 */
int PendingPush;  /* 0x001008b0 */
long Player1NumButtons;  /* 0x0010de64 */
float Player1Pos[SLOT_WORDS];  /* pointer slot -> 0x00150564 */
long Player1Wins;  /* 0x0014e204 */
long Player2NumButtons;  /* 0x0010de68 */
float Player2Pos[SLOT_WORDS];  /* pointer slot -> 0x00150570 */
float PlayerBright1;
long PlayerSelectToggle;  /* 0x00101720 */
char Players[SLOT_WORDS];  /* 0x001fa4d4 */
void *PortraitBorderTexture;  /* 0x00183f2c */
char PreloadedCharacters[SLOT_WORDS][PRELOAD_STRIDE];  /* 0x0028bc10 */
float RealBGSceneMatrix[32];  /* 0x001abaa0, two 4x4 */
float RenderMeshAlphaOverRide;  /* 0x0014e238 */
unsigned char *RenderRGBs;  /* slot -> 0x00366d88 */
int RenderSettings[2];  /* 0x001ab678, two words */
limeVECTOR2 *RenderUVs;  /* slot -> 0x003498c8 */
long Round;  /* 0x0014e228 */
long RoundHasEndedStatsUpdated;  /* 0x0014e244 */
long RoundSummary;  /* 0x0014e224 */
float RoundSummaryTime;  /* 0x0014e220 */
long RoundWins[2];  /* 0x0014e22c */
long SFXHandle[SLOT_WORDS];  /* 0x001ab99c -- an ARRAY of sound handles. */
long SaveData[SLOT_WORDS];  /* 0x001f439c */
float SceneScale;  /* 0x0014dfd8 .. */
float SceneScale2;  /* 0x0014dfe8 .. */
float SceneX;  /* 0x0014dfd8 .. */
float SceneX2;  /* 0x0014dfe8 .. */
float SceneY;  /* 0x0014dfd8 .. */
float SceneY2;  /* 0x0014dfe8 .. */
float SceneZ;  /* 0x0014dfd8 .. */
float SceneZ2;  /* 0x0014dfe8 .. */
void *SelectBGTexture;  /* 0x00183f24 */
int Settings[10];  /* 0x00100e34 */
float ShadowHeightFromGround;  /* 0x00171364 */
float ShadowOffset;  /* pointer slot -> 0x0014dfc8 */
float ShakeOffset[3];  /* 0x001f44bc */
long Single_Player_NextTask;  /* 0x00100e90 */
long *SizeofIntroLists;  /* 0x0014e070 */
void *SmashThruScene;  /* 0x001aba74 */
float SmokeAdjust;  /* 0x0016f77c */
float SmokeAdjust2;  /* 0x0016f780 */
float SmokeAdjustZ;  /* 0x0016f778 */
float SmokeCounter;  /* 0x00101724 */
void *SmokeEarthTexture;  /* 0x001ab66c */
void *SmokeExplosionTexture;  /* 0x001ab670 */
void *SmokeStarFieldTexture;  /* 0x001ab668 */
long SnapCam;  /* 0x00150e90 */
long SoundListUniqueCounter;  /* 0x0017b3b0 */
long SoundListUniqueHandle[SLOT_WORDS];
long SoundListUniqueIds[SLOT_WORDS];  /* the ids, one word each */
char SoundListUniqueNames[SLOT_WORDS];  /* 0x003878b0, stride 32 */
float SpearEndPos[2][3];  /* 0x001ab624 */
float SpearStartPos[2][3];  /* 0x001ab63c */
void *SpearTexture[SLOT_WORDS];  /* 0x001ab654 */
long SpearWhichTexture[2];  /* 0x0010def4 */
long SpeedNormal;  /* 0x0014e1f8 */
long SplashCount;  /* 0x00150cc8 */
void *SplashTexture1;  /* 0x001abb8c */
void *SplashTexture2;  /* 0x001abb90 */
void *SpotlightTextures[2];  /* 0x00183f14 */
int Stage;  /* 0x0014e214 */
long StatsNames[SLOT_WORDS];  /* 0x00100fdc */
long StatsPage;  /* 0x00100fd8 */
char Stats_[SLOT_WORDS];  /* see Write_Stats; 0x00183c84 */
long StrykerCharacters[4];  /* 0x001ab004 */
long SurvivalCharacter1;  /* 0x000ff990 */
long SurvivalStage;  /* 0x000ff980 */
long *SurvivalStageP;
int *SurvivalStagePtr;  /* slot -> 0x000ff980 */
float SwapLayers;
void *TPages[6];  /* 0x001f40ac */
void (*TaskFunctionList[SLOT_WORDS])(void);  /* 0x0017d940 */
float TestScale;  /* 0x0014e268 */
int TipToDisplay;  /* 0x001f44d0 */
long ToggleDebug;  /* 0x00150588 */
long Touch_About1;  /* 0x00100f58.. */
long Touch_About2;  /* 0x00100f58.. */
long Touch_About3;  /* 0x00100f58.. */
long Touch_About4;
long Touch_About5;
long Touch_About6;
long Touch_Extras1;  /* 0x00100f00.. */
long Touch_Extras2;  /* 0x00100f00.. */
long Touch_Extras3;  /* 0x00100f00.. */
long Touch_Extras4;
long Touch_Extras5;
long Touch_Extras6;
long Touch_MMExtra;  /* 0x00100e68 */
long Touch_MMHelp;  /* 0x00100e64 */
long Touch_MMMore;  /* 0x00100e6c */
long Touch_MMOptions;  /* 0x00100e5c */
long Touch_MMPlay;  /* 0x00100e60 */
long Touch_Options1;  /* 0x00100edc */
long Touch_Options2;  /* 0x00100ee0 */
long Touch_Options3;  /* 0x00100ee4 */
long Touch_Pause1;  /* 0x00151038.. */
long Touch_Pause2;  /* 0x00151038.. */
long Touch_Pause3;  /* 0x00151038.. */
long Touch_Pause4;
long Touch_Pause5;
long Touch_Pause6;
long Touch_PlayArcade;  /* 0x00100e80 */
long Touch_PlayMultiPlayer;  /* 0x00100e84 */
long Touch_PlaySK;  /* 0x00100e8c */
long Touch_PlaySurvival;  /* 0x00100e88 */
float TowerBGMatrix[16];  /* 0x0018ed80 */
int TowerData[SLOT_WORDS];  /* the table Load_Tower fills */
float TowerFireCount;  /* 0x00101760 */
void *TowerPortraitTexture[28];  /* 0x00183e88 */
float TowerPulledPos[3];  /* 0x00101728 */
long TowerRand[SLOT_WORDS];  /* 0x001014d0 */
float TowerSelect1BottomPos[3];  /* 0x00101740 */
float TowerSelect1TopPos[3];  /* 0x00101734 */
long TowerState;  /* 0x000ff9ac */
float TowerWait;  /* 0x00101750 */
float TrainingBadMessage;  /* 0x001780a4 */
long TrainingCatagory;  /* 0x0017809c */
TRAININGMOVE TrainingData[SLOT_WORDS];  /* 0x001782e8 */
float TrainingGoodMessage;  /* 0x001780a0 */
long TrainingMoveCount;  /* 0x001780a8 */
const char *TrainingNames[SLOT_WORDS];  /* pointer slot -> 0x00176718 */
int *TreasureGained;  /* slot -> 0x00101164, see Reset_SaveData */
long TreasurePlayed;  /* 0x000ff8bc */
float TreasureSelectTime;  /* 0x0010118c */
long TreasureSelected;  /* 0x00101160 */
long UCPtr;  /* 0x00178034 */
long *UpperLowerTxt;  /* 0x0015107c */
int *UseLOWAssetsPtr;  /* slot -> 0x0010df10 */
int VSAssetsLoaded;  /* 0x000ff9a8 */
float VSScroll;  /* 0x000ff9a4 */
void *VSTexture;  /* 0x00183f10 */
float VSWait;  /* 0x000ff9a0 -- a FLOAT: FE_Task_VS_Screen */
char *Versus_Names[SLOT_WORDS];  /* 0x000ffbf4 */
char *Versus_Names2[SLOT_WORDS];  /* 0x000ffe74 */
char *Versus_Names2_LOW[SLOT_WORDS];  /* 0x00100420 */
char *Versus_Names_LOW[SLOT_WORDS];  /* 0x00100140 */
MKMOVE VeteranMoves[SLOT_WORDS];  /* 0x0015059c, also 12 bytes an entry */
void *Vortex1Texture;  /* 0x00183e7c */
void *Vortex2Texture;  /* 0x00183e80 */
float VortexScale;  /* 0x00101754 */
float VortexSpin;  /* 0x0010174c */
signed char WantFrames[SLOT_WORDS];  /* 0x00295d24, WANTFRAMES_BYTES of them */
long WantedFrames[SLOT_WORDS];  /* 0x00295cd4, terminated by -1 */
void *WhiteTexture;  /* 0x001ab998 */
long WinsNeeded;  /* 0x0014e234 */
float WorldScaleAdjust;  /* pointer slot -> 0x0014df9c */
char __mh_execute_header;
int achievementTracker[24];  /* 0x00379c60, see achievements.c */
float averageScaleFactor;  /* 0x001017b0 */
long averageScaleFactorCnt;  /* 0x001017b4 */
float averageScaleFactorOutput;  /* 0x001017b8 -- written, never read */
float blood_lrscale;  /* 0x0016f75c */
float blood_minxvel;  /* 0x0016f750 */
float blood_xvs;  /* 0x0016f760 */
float blood_yoff;  /* 0x0016f758 */
float blood_zoff;  /* 0x0016f754 */
long boyrand;  /* 0x0010de6c, 0x0010de70 */
long boyrand2;  /* 0x0010de6c, 0x0010de70 */
float camheight;  /* 0x0014dff0 -- the compiler */
float camlookatheight;
float camzoomedin;  /* 0x0014dfb4 */
float camzoomedout;  /* 0x0014dfb8 */
long charSelectButtonPressed;  /* 0x00100eb8 */
long characterReported;  /* 0x000ff7fc */
long currentAchievementPage;  /* 0x000ff96c */
float currentBiosProgress;  /* 0x00101080 */
float currentEndingProgress;  /* 0x00101150 */
long currentLeaderBoardPage;  /* 0x000ff8e8 */
long currentLeaderboard;  /* 0x00100fd4 */
long currentMPJoystickData;  /* 0x0014e26c */
long currentMPSpriteList;  /* 0x0014e270 */
long currentPeriod;  /* 0x000ff8e4 */
long displayTicker;  /* 0x001008a0 */
float distzoomedin;  /* 0x0014dfbc */
float distzoomedout;  /* 0x0014dfc0 */
char dummyObjects[SLOT_WORDS];  /* 0x0010de84 */
float exitTimeout;  /* 0x00182c80 */
long explosion_Anim[SLOT_WORDS];  /* pointer slot -> 0x0017cec8 */
char explosion_SpriteDef[SLOT_WORDS];  /* pointer slot -> 0x0017cac8 */
long fatal_HUDgfx_Anim[SLOT_WORDS];  /* pointer slot -> 0x0017c81c; the slot */
char fatal_HUDgfx_SpriteDef[SLOT_WORDS];  /* pointer slot -> 0x0017b9dc */
long feedPosted;  /* 0x00100e30 */
float finishsize;  /* 0x00175184 */
FOUNDTOKEN foundToken;  /* 0x003877e0 */
long g_usprintfSemaphore;  /* 0x00178078 */
long gameCnt;  /* 0x00150ea0 */
long girlrand;  /* 0x0010de74, 0x0010de78 */
long girlrand2;  /* 0x0010de74, 0x0010de78 */
long groundoffsets[SLOT_WORDS];  /* 0x001725bc */
long group_choices[SLOT_WORDS];  /* 0x0017b2e0 */
long *group_table[SLOT_WORDS];  /* 0x0017b308 */
SOUNDENTRY gs_attack[SLOT_WORDS];
SOUNDENTRY gs_death[SLOT_WORDS];
SOUNDENTRY gs_face_hit_voice[SLOT_WORDS];
SOUNDENTRY gs_grab[SLOT_WORDS];
SOUNDENTRY gs_jump[SLOT_WORDS];
SOUNDENTRY gs_run[SLOT_WORDS];
SOUNDENTRY gs_shook[SLOT_WORDS];
SOUNDENTRY gs_slam[SLOT_WORDS];
SOUNDENTRY gs_tripped_voice[SLOT_WORDS];
SOUNDENTRY gs_wasted[SLOT_WORDS];
long hideTicker;  /* 0x001008a4 */
long highestQueueNum;  /* 0x00150ea8 */
KODE kodes[SLOT_WORDS];  /* 0x00176c04 */
long lastChar;  /* 0x000ff9e8 */
long lastCharDelay;  /* 0x000ff9ec */
long lastJoybits;  /* 0x00150ea4 */
long lastSpritelistIndex;  /* 0x0010dec8 */
int lastTimerTimestamp;  /* 0x000ff8d8 */
long lastWinStreak;  /* 0x0014e1ac */
long lastopponentCharacter;  /* 0x0010171c */
long leaderboardPageCnt;  /* 0x000ff8ec */
long leaderboardsConnectionAVailable;  /* 0x00100f94 */
long leaderboardsInit;  /* 0x00100f98 */
long leaderboardsInitSK;  /* 0x00100f9c */
TOKEN listOfTokens[SLOT_WORDS];  /* 0x003877f0 */
long lobbyInfoFade;  /* 0x000ff808 */
long lobbyInfoTxt;  /* 0x000ff80c */
float m[SLOT_WORDS];  /* 0x00370dd8, the scratch matrix */
float mmfontcol[SLOT_WORDS];  /* 0x000ff854, sixteen bytes an entry */
float mpBlinker;  /* 0x00100eb0 */
char mpEventQueue[0x1b0];  /* 0x001ab7c0 */
int mpLevelList[SLOT_WORDS];  /* 0x000ddffc, file-local in the original */
long mpLobbyCurrentPage;  /* 0x000ff8e0 */
long mpOpponentJoystickInput[SLOT_WORDS];  /* 0x001ab970, two words an entry */
char mpSpriteList[0x140];  /* 0x001ab680 */
float mxvelx;  /* 0x0014dfb0 */
BUTTONNEW nameEntryButtons[SLOT_WORDS];  /* 0x0010058c, twenty bytes an entry */
long nameIndex;  /* 0x000ff9e4 */
long newGameFlag;  /* 0x000ff850 */
long nextBiosPage;  /* 0x00101084 */
long nextEndingsPage;  /* 0x00101154 */
CSOUNDENTRY *ochar_sound_tables[SLOT_WORDS];  /* 0x0017b278 */
int opponentCharacter;  /* 0x000ff998 */
long opponentFPS2;  /* 0x0014e1e4 */
long opponentPressedPlay;  /* 0x000ff828 */
char ourCharacters[SLOT_WORDS];  /* 0x000ff9c8, NUL-terminated */
char ourName[SLOT_WORDS];  /* 0x00183d6c */
char peerNames[PEER_ROWS][PEER_STRIDE];  /* 0x00185730 */
int peerNamesFlags[8];  /* 0x00185930 */
int playerCharacter;  /* 0x000ff99c */
long playerLostRound;  /* 0x000ff8b8 */
long points;  /* 0x0014e1b0 */
long pressedPlay;  /* 0x000ff824 */
float psp_maxdist;  /* 0x0014dfa8 */
float psp_off;  /* 0x0014dfa4 */
float psp_scale;  /* 0x0014dfa0 */
int randomKode;  /* 0x00151084 */
long restartConnectionFlag;  /* 0x000ff8c4 */
long rsnd_choices[SLOT_WORDS];  /* 0x0017b370, one count per id */
long *rsnd_table[SLOT_WORDS];  /* 0x0017b330, one row array per id */
long sendInd;  /* 0x00100ebc */
long sindelFlying;  /* 0x0014dff8 */
long socialConnectionAvailable;  /* 0x00100e2c */
SOUNDENTRY st_fn[SLOT_WORDS];
SOUNDENTRY st_indian[SLOT_WORDS];
SOUNDENTRY st_jax[SLOT_WORDS];
SOUNDENTRY st_kano[SLOT_WORDS];
SOUNDENTRY st_lao[SLOT_WORDS];
SOUNDENTRY st_lia[SLOT_WORDS];
SOUNDENTRY st_lk[SLOT_WORDS];
SOUNDENTRY st_motaro[SLOT_WORDS];
SOUNDENTRY st_nj[SLOT_WORDS];
SOUNDENTRY st_robo1[SLOT_WORDS];
SOUNDENTRY st_sg[SLOT_WORDS];
SOUNDENTRY st_sk[SLOT_WORDS];
SOUNDENTRY st_sonya[SLOT_WORDS];
SOUNDENTRY st_st[SLOT_WORDS];
SOUNDENTRY st_subzero[SLOT_WORDS];
SOUNDENTRY st_swat[SLOT_WORDS];
SOUNDENTRY st_tusk[SLOT_WORDS];
long startDebug;  /* 0x000ff800 */
long stats[SLOT_WORDS];  /* 0x00100fc8 */
char str[SLOT_WORDS];  /* 0x001f3cac, the shared scratch buffer */
long survivalWinStreak;  /* 0x0014e1ec */
float swivelscale;  /* 0x001f44a0 */
int syncCharacters;  /* 0x000ff814 */
int syncCharactersOpponent;  /* 0x000ff818 */
SOUNDENTRY tab_rsnd_big_block[SLOT_WORDS];
SOUNDENTRY tab_rsnd_big_smack[SLOT_WORDS];
SOUNDENTRY tab_rsnd_big_whoosh[SLOT_WORDS];
SOUNDENTRY tab_rsnd_body_hit[SLOT_WORDS];
SOUNDENTRY tab_rsnd_enemy_boom[SLOT_WORDS];
SOUNDENTRY tab_rsnd_footstep[SLOT_WORDS];
SOUNDENTRY tab_rsnd_ground[SLOT_WORDS];
SOUNDENTRY tab_rsnd_klang[SLOT_WORDS];
SOUNDENTRY tab_rsnd_med_smack[SLOT_WORDS];
SOUNDENTRY tab_rsnd_rocks[SLOT_WORDS];
SOUNDENTRY tab_rsnd_sk_bonus_win[SLOT_WORDS];
SOUNDENTRY tab_rsnd_smack[SLOT_WORDS];
SOUNDENTRY tab_rsnd_small_block[SLOT_WORDS];
SOUNDENTRY tab_rsnd_splish[SLOT_WORDS];
SOUNDENTRY tab_rsnd_stab[SLOT_WORDS];
SOUNDENTRY tab_rsnd_whoosh[SLOT_WORDS];
long thisSessionId;  /* 0x000ff81c */
long tickerLoaded;  /* 0x001008a8 */
float tickeroff;  /* 0x000ff8d4 */
float timeInGame;  /* 0x0014e1e0 */
long towerFinishedAndLogged;  /* 0x0010de60 */
long triple_sndtab[SLOT_WORDS][2];  /* 0x001790b8, stride 8 */
long userNameEntryViewed;  /* 0x000ff8f0 */
char *usprintfBuffers[16];  /* 0x00178038 */
float vsScreenTimer;  /* 0x000ff8dc */
long winStreak;  /* 0x0014e1a8 */
long winningStryk;  /* 0x0014dffc */
long workingInd;  /* 0x000ff810 */
float zoomedoutweight;  /* 0x001f44a4 */

/* ---- 154 pointer slots: storage, then a pointer at it ---- */

static long AnimalityMessage__store[SLOT_WORDS];
long *AnimalityMessage = AnimalityMessage__store;
static long BabalityMessage__store[SLOT_WORDS];
long *BabalityMessage = BabalityMessage__store;
static void *BloodScene__store[SLOT_WORDS];
void **BloodScene = BloodScene__store;
static void *BloodTextures__store[SLOT_WORDS];
void **BloodTextures = BloodTextures__store;
static float ButtonSize__store[SLOT_WORDS];
float *ButtonSize = ButtonSize__store;
static void *ButtonsTPage__store[SLOT_WORDS];
void **ButtonsTPage = ButtonsTPage__store;
static long CamTrackToPlayer__store[SLOT_WORDS];
long *CamTrackToPlayer = CamTrackToPlayer__store;
static float CameraLookAt__store[SLOT_WORDS];
float *CameraLookAt = CameraLookAt__store;
static long Character2__store[SLOT_WORDS];
long *Character2 = Character2__store;
static const char *CharacterNames__store[SLOT_WORDS];
const char **CharacterNames = CharacterNames__store;
static long ClockSingles__store[SLOT_WORDS];
long *ClockSingles = ClockSingles__store;
static long ClockTens__store[SLOT_WORDS];
long *ClockTens = ClockTens__store;
static long ComboDamage__store[SLOT_WORDS];
long *ComboDamage = ComboDamage__store;
static long ComboNumber__store[SLOT_WORDS];
long *ComboNumber = ComboNumber__store;
static float ComboSlider1__store[SLOT_WORDS];
float *ComboSlider1 = ComboSlider1__store;
static float ComboSlider2__store[SLOT_WORDS];
float *ComboSlider2 = ComboSlider2__store;
static float ComboTimer__store[SLOT_WORDS];
float *ComboTimer = ComboTimer__store;
static int CurrentTaskPtr__store[SLOT_WORDS];
int *CurrentTaskPtr = CurrentTaskPtr__store;
static void *CyraxSelfDestructScene__store[SLOT_WORDS];
void **CyraxSelfDestructScene = CyraxSelfDestructScene__store;
static long DangerMessage__store[SLOT_WORDS];
long *DangerMessage = DangerMessage__store;
static long Destiny__store[SLOT_WORDS];
long *Destiny = Destiny__store;
static const char *DestinyNames__store[SLOT_WORDS];
const char **DestinyNames = DestinyNames__store;
static const char *DestinyNamesWin__store[SLOT_WORDS];
const char **DestinyNamesWin = DestinyNamesWin__store;
static int DoIntroPtr__store[SLOT_WORDS];
int *DoIntroPtr = DoIntroPtr__store;
static long DoingSKDeath__store[SLOT_WORDS];
long *DoingSKDeath = DoingSKDeath__store;
static long DoingStageFatal__store[SLOT_WORDS];
long *DoingStageFatal = DoingStageFatal__store;
static long EndingsText__store[SLOT_WORDS];
long *EndingsText = EndingsText__store;
static long EnduranceChange__store[SLOT_WORDS];
long *EnduranceChange = EnduranceChange__store;
static long EnduranceCharacters__store[SLOT_WORDS];
long *EnduranceCharacters = EnduranceCharacters__store;
static long EnduranceTowerList__store[SLOT_WORDS];
long *EnduranceTowerList = EnduranceTowerList__store;
static void *FBIconTexture__store[SLOT_WORDS];
void **FBIconTexture = FBIconTexture__store;
static void *FBLoginTexture__store[SLOT_WORDS];
void **FBLoginTexture = FBLoginTexture__store;
static void *FBLogoutTexture__store[SLOT_WORDS];
void **FBLogoutTexture = FBLogoutTexture__store;
static void *FEBackground__store[SLOT_WORDS];
void **FEBackground = FEBackground__store;
static void *FEBits1__store[SLOT_WORDS];
void **FEBits1 = FEBits1__store;
static void *FEBits2__store[SLOT_WORDS];
void **FEBits2 = FEBits2__store;
static void *FEBits3__store[SLOT_WORDS];
void **FEBits3 = FEBits3__store;
static float FE_FadeAddP__store[SLOT_WORDS];
float *FE_FadeAddP = FE_FadeAddP__store;
static float FE_HeightScaleP__store[SLOT_WORDS];
float *FE_HeightScaleP = FE_HeightScaleP__store;
static float FE_WidthScaleP__store[SLOT_WORDS];
float *FE_WidthScaleP = FE_WidthScaleP__store;
static float FaceMeMatrix__store[SLOT_WORDS];
float *FaceMeMatrix = FaceMeMatrix__store;
static long FatalityMessage__store[SLOT_WORDS];
long *FatalityMessage = FatalityMessage__store;
static long FightMessage__store[SLOT_WORDS];
long *FightMessage = FightMessage__store;
static long FinishHimHer__store[SLOT_WORDS];
long *FinishHimHer = FinishHimHer__store;
static int FrameCountPtr__store[SLOT_WORDS];
int *FrameCountPtr = FrameCountPtr__store;
static long FrameRemapTable__store[SLOT_WORDS];
long *FrameRemapTable = FrameRemapTable__store;
static long *FrameRemapTablePtr__store[SLOT_WORDS];
long **FrameRemapTablePtr = FrameRemapTablePtr__store;
static long FriendshipMessage__store[SLOT_WORDS];
long *FriendshipMessage = FriendshipMessage__store;
static float GameCounter__store[SLOT_WORDS];
float *GameCounter = GameCounter__store;
static void *GameFont__store[SLOT_WORDS];
void *GameFont = GameFont__store;
static void *GameFontP__store[SLOT_WORDS];
void *GameFontP = GameFontP__store;
static void *GameFontSlot__store[SLOT_WORDS];
void **GameFontSlot = GameFontSlot__store;
static long GameMode__store[SLOT_WORDS];
long *GameMode = GameMode__store;
static void *GameObjects__store[SLOT_WORDS];
void **GameObjects = GameObjects__store;
static long GamePaused__store[SLOT_WORDS];
long *GamePaused = GamePaused__store;
static long GamePausedPtr__store[SLOT_WORDS];
long *GamePausedPtr = GamePausedPtr__store;
static void *GreenFrameTexture__store[SLOT_WORDS];
void **GreenFrameTexture = GreenFrameTexture__store;
static long H__store[SLOT_WORDS];
long *H = H__store;
static long Health__store[SLOT_WORDS];
long *Health = Health__store;
static float IdentityMatrix__store[SLOT_WORDS];
float *IdentityMatrix = IdentityMatrix__store;
static long *IdleLists__store[SLOT_WORDS];
long **IdleLists = IdleLists__store;
static long InGameLevelSelect__store[SLOT_WORDS];
long *InGameLevelSelect = InGameLevelSelect__store;
static long IsInFinishing__store[SLOT_WORDS];
long *IsInFinishing = IsInFinishing__store;
static long KarnageScore__store[SLOT_WORDS];
long *KarnageScore = KarnageScore__store;
static long LastDestiny__store[SLOT_WORDS];
long *LastDestiny = LastDestiny__store;
static char *LevelInfoPtr__store[SLOT_WORDS];
char **LevelInfoPtr = LevelInfoPtr__store;
static long LevelSelect__store[SLOT_WORDS];
long *LevelSelect = LevelSelect__store;
static long LevelSelectP__store[SLOT_WORDS];
long *LevelSelectP = LevelSelectP__store;
static int LevelSelectPtr__store[SLOT_WORDS];
int *LevelSelectPtr = LevelSelectPtr__store;
static long LockCamera__store[SLOT_WORDS];
long *LockCamera = LockCamera__store;
static MKEVENTQUEUE MKEventQueue__store[SLOT_WORDS];
MKEVENTQUEUE *MKEventQueue = MKEventQueue__store;
static float *MatrixPalette2__store[SLOT_WORDS];
float **MatrixPalette2 = MatrixPalette2__store;
static long MercyMessage__store[SLOT_WORDS];
long *MercyMessage = MercyMessage__store;
static void *MeshSet_FIGHT__store[SLOT_WORDS];
void *MeshSet_FIGHT = MeshSet_FIGHT__store;
static long NextTask__store[SLOT_WORDS];
long *NextTask = NextTask__store;
static long OpponentTowerList__store[SLOT_WORDS];
long *OpponentTowerList = OpponentTowerList__store;
static long P2Controls__store[SLOT_WORDS];
long *P2Controls = P2Controls__store;
static long PLAYER1MODEL__store[SLOT_WORDS];
long *PLAYER1MODEL = PLAYER1MODEL__store;
static long PLAYER2MODEL__store[SLOT_WORDS];
long *PLAYER2MODEL = PLAYER2MODEL__store;
static void *PitDeathScene__store[SLOT_WORDS];
void **PitDeathScene = PitDeathScene__store;
static long Player2NumButtonsP__store[SLOT_WORDS];
long *Player2NumButtonsP = Player2NumButtonsP__store;
static char PlayerDefs__store[SLOT_WORDS];
char *PlayerDefs = PlayerDefs__store;
static char *PlayerDefsPtr__store[SLOT_WORDS];
char **PlayerDefsPtr = PlayerDefsPtr__store;
static float PlayerSize__store[SLOT_WORDS];
float *PlayerSize = PlayerSize__store;
static float PlayerZPosPtr__store[SLOT_WORDS];
float *PlayerZPosPtr = PlayerZPosPtr__store;
static char PlayersP__store[SLOT_WORDS];
char *PlayersP = PlayersP__store;
static void *RedFrameTexture__store[SLOT_WORDS];
void **RedFrameTexture = RedFrameTexture__store;
static limeVECTOR3 RenderVerts__store[SLOT_WORDS];
limeVECTOR3 *RenderVerts = RenderVerts__store;
static void *RocksScene__store[SLOT_WORDS];
void **RocksScene = RocksScene__store;
static long RoundHasEnded__store[SLOT_WORDS];
long *RoundHasEnded = RoundHasEnded__store;
static long RoundMessage__store[SLOT_WORDS];
long *RoundMessage = RoundMessage__store;
static long RoundParam__store[SLOT_WORDS];
long *RoundParam = RoundParam__store;
static long RunBar__store[SLOT_WORDS];
long *RunBar = RunBar__store;
static float SKDeathMessageOffset__store[SLOT_WORDS];
float *SKDeathMessageOffset = SKDeathMessageOffset__store;
static void *SKEffectScene__store[SLOT_WORDS];
void **SKEffectScene = SKEffectScene__store;
static void *SLDie1Scene__store[SLOT_WORDS];
void **SLDie1Scene = SLDie1Scene__store;
static void *SLDie2Scene__store[SLOT_WORDS];
void **SLDie2Scene = SLDie2Scene__store;
static void *SZEffectScene__store[SLOT_WORDS];
void **SZEffectScene = SZEffectScene__store;
static float SceneGroundOffset__store[SLOT_WORDS];
float *SceneGroundOffset = SceneGroundOffset__store;
static long SceneRenderAlwaysTrans__store[SLOT_WORDS];
long *SceneRenderAlwaysTrans = SceneRenderAlwaysTrans__store;
static void *Scene_FIGHT__store[SLOT_WORDS];
void *Scene_FIGHT = Scene_FIGHT__store;
static float ScorpionFade__store[SLOT_WORDS];
float *ScorpionFade = ScorpionFade__store;
static float ScorpionFadeAdd__store[SLOT_WORDS];
float *ScorpionFadeAdd = ScorpionFadeAdd__store;
static float ScorpionFlash__store[SLOT_WORDS];
float *ScorpionFlash = ScorpionFlash__store;
static long SizeofIdleLists__store[SLOT_WORDS];
long *SizeofIdleLists = SizeofIdleLists__store;
static long SkipFrame86__store[SLOT_WORDS];
long *SkipFrame86 = SkipFrame86__store;
static void *SmokeTexture__store[SLOT_WORDS];
void **SmokeTexture = SmokeTexture__store;
static long SpritelistReceived__store[SLOT_WORDS];
long *SpritelistReceived = SpritelistReceived__store;
static float StaticMeshAmbient__store[SLOT_WORDS];
float *StaticMeshAmbient = StaticMeshAmbient__store;
static long Stats__store[SLOT_WORDS];
long *Stats = Stats__store;
static long SurvivalHealth__store[SLOT_WORDS];
long *SurvivalHealth = SurvivalHealth__store;
static long SurvivalStageP2__store[SLOT_WORDS];
long *SurvivalStageP2 = SurvivalStageP2__store;
static void *SwatEffectScene__store[SLOT_WORDS];
void **SwatEffectScene = SwatEffectScene__store;
static char TheFECharacters__store[SLOT_WORDS];
char *TheFECharacters = TheFECharacters__store;
static void *TrainDie1Scene__store[SLOT_WORDS];
void **TrainDie1Scene = TrainDie1Scene__store;
static void *TrainDie2Scene__store[SLOT_WORDS];
void **TrainDie2Scene = TrainDie2Scene__store;
static void *TrainScene__store[SLOT_WORDS];
void **TrainScene = TrainScene__store;
static long TrainingCatagoryP__store[SLOT_WORDS];
long *TrainingCatagoryP = TrainingCatagoryP__store;
static long UseLOWAssets__store[SLOT_WORDS];
long *UseLOWAssets = UseLOWAssets__store;
static long WaitForOpponent__store[SLOT_WORDS];
long *WaitForOpponent = WaitForOpponent__store;
static long WantDoingFatalFrames__store[SLOT_WORDS];
long *WantDoingFatalFrames = WantDoingFatalFrames__store;
static char WinnerMessage__store[SLOT_WORDS];
char *WinnerMessage = WinnerMessage__store;
static void *XeroxScene__store[SLOT_WORDS];
void **XeroxScene = XeroxScene__store;
static FEACHIEVEMENTDESCR achievementsDescr__store[SLOT_WORDS];
FEACHIEVEMENTDESCR *achievementsDescr = achievementsDescr__store;
static long blast_player_height__store[SLOT_WORDS];
long *blast_player_height = blast_player_height__store;
static long blast_state__store[SLOT_WORDS];
long *blast_state = blast_state__store;
static float col__store[SLOT_WORDS];
float *col = col__store;
static float darkcol__store[SLOT_WORDS];
float *darkcol = darkcol__store;
static long defeatedBySK__store[SLOT_WORDS];
long *defeatedBySK = defeatedBySK__store;
static float endingsOffsetY__store[SLOT_WORDS];
float *endingsOffsetY = endingsOffsetY__store;
static long endurancerand1__store[SLOT_WORDS];
long *endurancerand1 = endurancerand1__store;
static long endurancerand2__store[SLOT_WORDS];
long *endurancerand2 = endurancerand2__store;
static long flawlessVictories__store[SLOT_WORDS];
long *flawlessVictories = flawlessVictories__store;
static float fontcol__store[SLOT_WORDS];
float *fontcol = fontcol__store;
static float fontcolP__store[SLOT_WORDS];
float *fontcolP = fontcolP__store;
static int incomingQueueLenPtr__store[SLOT_WORDS];
int *incomingQueueLenPtr = incomingQueueLenPtr__store;
static int incomingQueueStartPtr__store[SLOT_WORDS];
int *incomingQueueStartPtr = incomingQueueStartPtr__store;
static const char *kodeNames__store[SLOT_WORDS];
const char **kodeNames = kodeNames__store;
static long lastTimestamp__store[SLOT_WORDS];
long *lastTimestamp = lastTimestamp__store;
static float lightsOn__store[SLOT_WORDS];
float *lightsOn = lightsOn__store;
static float midcol__store[SLOT_WORDS];
float *midcol = midcol__store;
static long opponentCharacterP__store[SLOT_WORDS];
long *opponentCharacterP = opponentCharacterP__store;
static long opponentPerformedMercy__store[SLOT_WORDS];
long *opponentPerformedMercy = opponentPerformedMercy__store;
static long otherPlayerPaused__store[SLOT_WORDS];
long *otherPlayerPaused = otherPlayerPaused__store;
static long readyToSync__store[SLOT_WORDS];
long *readyToSync = readyToSync__store;
static long requestedLevel__store[SLOT_WORDS];
long *requestedLevel = requestedLevel__store;
static float semicol__store[SLOT_WORDS];
float *semicol = semicol__store;
static float semidarkcol__store[SLOT_WORDS];
float *semidarkcol = semidarkcol__store;
static long spotlight_Anim__store[SLOT_WORDS];
long *spotlight_Anim = spotlight_Anim__store;
static void *spotlight_SpriteDef__store[SLOT_WORDS];
void **spotlight_SpriteDef = spotlight_SpriteDef__store;
static long startTime__store[SLOT_WORDS];
long *startTime = startTime__store;
static char strBuf__store[SLOT_WORDS];
char *strBuf = strBuf__store;
static long syncState__store[SLOT_WORDS];
long *syncState = syncState__store;
static long theKode__store[SLOT_WORDS];
long *theKode = theKode__store;

/* 672 plain + 154 slots = 826 */
