/* Generated by tools/mkglobals.py -- do not hand-edit.
 *
 * The struct layouts the decompiled globals need, scraped from the .c
 * files that established them. Copying them by hand would let the two
 * drift, and the offsets are the part that was expensive to prove.
 */

#ifndef GAMECODE_GLOBALS_H
#define GAMECODE_GLOBALS_H

#include <stdint.h>

typedef struct BARS BARS;
typedef struct BONESINFO BONESINFO;
typedef struct FLOAT FLOAT;
typedef struct FRONTEND_CHARACTER FRONTEND_CHARACTER;
typedef struct INVERTED INVERTED;
typedef struct KANO KANO;
typedef struct KANO_STANDARD KANO_STANDARD;
typedef struct LocaleManager LocaleManager;
typedef struct MESHSETINFO MESHSETINFO;
typedef struct Mk3Obj_t Mk3Obj_t;
typedef struct NOT NOT;
typedef struct ONE ONE;
typedef struct OPPOSITE OPPOSITE;
typedef struct SIGNED SIGNED;
typedef struct SKININFO SKININFO;
typedef struct limeMATRIX44 limeMATRIX44;
typedef struct limeVECTOR2 limeVECTOR2;

#ifndef ALLFRAMES_COUNT
#define ALLFRAMES_COUNT 0x1c4c
#endif
#ifndef ALLFRAMES_STRIDE
#define ALLFRAMES_STRIDE 0x41
#endif
#ifndef BIOS_PAGES
#define BIOS_PAGES 26
#endif
#ifndef CHARACTER_SLOTS
#define CHARACTER_SLOTS 26
#endif
#ifndef CS_COLS
#define CS_COLS 7
#endif
#ifndef CS_ROWS
#define CS_ROWS 4
#endif
#ifndef FE_CHARACTER_SLOTS
#define FE_CHARACTER_SLOTS 26
#endif
#ifndef FE_CHARACTER_STRIDE
#define FE_CHARACTER_STRIDE 0x668
#endif
#ifndef FRAME_REMAP_ENTRIES
#define FRAME_REMAP_ENTRIES 7245
#endif
#ifndef GAME_EVENT_SLOTS
#define GAME_EVENT_SLOTS 16
#endif
#ifndef GAME_EVENT_STRIDE
#define GAME_EVENT_STRIDE 0x64
#endif
#ifndef JADE
#define JADE 0x10
#endif
#ifndef JOY_DIRECTIONS
#define JOY_DIRECTIONS 9
#endif
#ifndef PARTICLE_COUNT
#define PARTICLE_COUNT (PARTICLE_POOL / PARTICLE_STRIDE)
#endif
#ifndef PARTICLE_POOL
#define PARTICLE_POOL 0x6000u
#endif
#ifndef PARTICLE_STRIDE
#define PARTICLE_STRIDE 0x30u
#endif
#ifndef PEER_ROWS
#define PEER_ROWS 8
#endif
#ifndef PEER_STRIDE
#define PEER_STRIDE 0x40
#endif
#ifndef PRELOAD_STRIDE
#define PRELOAD_STRIDE 0x5f4
#endif
#ifndef SINDEL
#define SINDEL 6
#endif
#ifndef WANTFRAMES_BYTES
#define WANTFRAMES_BYTES 0x1c4c
#endif

typedef struct ANIMATEDCHARACTER {
    long        meshCount;      /* 0x00 */
    void       *meshes;         /* 0x04  meshCount records of 0x58 */
    long        id;             /* 0x08  the character, for the frame gates */
    long        field0c;        /* 0x0c  nothing reads it */
    void       *scene;          /* 0x10 */
    void       *diffuse;        /* 0x14 */
    void       *diffuseIce;     /* 0x18 */
    void       *jadeGreen;      /* 0x1c  JADE only */
    void       *sindelHair;     /* 0x20  SINDEL only */
    void       *diffuse2;       /* 0x24  the lite path's second sheet */
    void       *babality;       /* 0x28  may stay NULL */
    void       *frameList;      /* 0x2c */
    void       *skin;           /* 0x30 */
    void       *bones;          /* 0x34 */
    const long *meshbase;       /* 0x38  kept so it can be freed */
    const long *meshTable;      /* 0x3c */
    const long *meshNames;      /* 0x40 */
} ANIMATEDCHARACTER;            /* 0x44 = 68 bytes, the size limeMalloc asks */

struct BUTTONNEW {
    long  style;                        /* 0x00, 0..8; anything else is a
                                         *       full-texture fallback */
    long  w;                            /* 0x04 */
    long  h;                            /* 0x08 */
    short thickness;                    /* 0x0c, for the red highlight */
    short pad;                          /* 0x0e */
    float pressed;                      /* 0x10, set to 1.0f on release */
};
typedef struct BUTTONNEW BUTTONNEW;

typedef struct CREDITSENTRY {
    long id;                            /* 0x00, -1 leaves the row blank */
    long scale10;                       /* 0x04 */
} CREDITSENTRY;

typedef struct CSOUNDENTRY {
    uint32_t field00;            /* 0x00 */
    uint32_t field04;            /* 0x04  what get_csound returns */
} CSOUNDENTRY;

typedef struct EDITVAR {
    long        pad;                    /* 0x00 */
    const char *label;                  /* 0x04 */
    void       *target;                 /* 0x08 */
    float       lower;                  /* 0x0c */
    float       step;                   /* 0x10 */
    long        type;                   /* 0x14, 0 = heading */
} EDITVAR;

typedef struct FEACHIEVEMENTDESCR {
    long id;                            /* 0x00  GameText id of the name */
    long descr;                         /* 0x04  GameText id of the description */
    long pad08;                         /* 0x08 */
    long timer;                         /* 0x0c */
} FEACHIEVEMENTDESCR;

typedef struct FOUNDTOKEN {
    long        type;                   /* 0x00  0 none, 1 's', 2 'd', 4 'f' */
    long        index;                  /* 0x04  0..7 from the digit, -1 if none */
    long        unknown;                /* 0x08 */
    const char *at;                     /* 0x0c  the unit the type char sits on */
} FOUNDTOKEN;

typedef struct GAMEEVENT {
    int32_t active;                     /* 0x00  the only field this file touches */
    uint8_t rest[GAME_EVENT_STRIDE - 4];
} GAMEEVENT;

typedef struct GAMESTATE {
    uint8_t _pad000[0x368];
    /* The two health BARS, and they are the health scaled by 1.66 -- see
     * ResetFightData, which writes 166/83/41 beside health 100/50/25 and
     * computes the survival one as `Health[0] * 166 / 100`. */
    long    healthBar1;                 /* 0x368 */
    long    healthBar2;                 /* 0x36c */
    uint8_t _pad370[0x44e - 0x370];
    int16_t field44e;                   /* 0x44e  ldrsh, normalised to 0 or 1 */
} GAMESTATE;

typedef struct {
    float       speed;      /* idle playback rate: 1.0f, and 0.5f for a few */
    const long *frames;     /* frame numbers, terminated by -1 */
} IdleSet;

typedef struct KODE {
    long seq[6];                        /* 0x00 .. 0x14 */
    long unused;                        /* 0x18, never read by checkIfKode */
    long value;                         /* 0x1c */
} KODE;

typedef struct MKEVENT {
    signed char type;
    signed char player;
    signed char subtype;
    signed char pad;
    int32_t     param;
} MKEVENT;

typedef struct MKEVENTQUEUE {
    int32_t count;
    MKEVENT event[1];
} MKEVENTQUEUE;

typedef struct MKMOVE {
    long unused;                        /* 0x00 */
    long mask;                          /* 0x04  the bit pattern to match */
    long index;                         /* 0x08  into _VeteranMoves */
} MKMOVE;

typedef struct {
    long        rows;
    long        nameId;                 /* GameText base A */
    long        captionId;              /* GameText base B */
    const long *moves5;
    const long *moves6;
} MOVESSECTION;

typedef struct PARTICLE {
    float    field00;            /* 0x00  a size, four steps of PSize/4 */
    float    field04;            /* 0x04  set together with field08, same value */
    float    field08;            /* 0x08  the free marker InitParticles clears */
    int32_t  field0c;            /* 0x0c  the type AddParticles was called with */
    float    field10;            /* 0x10  x, passed straight through */
    float    field14;            /* 0x14  y + blood_zoff */
    float    field18;            /* 0x18  z + blood_yoff */
    uint8_t  _pad1c[4];          /* 0x1c  not touched by AddParticles */
    float    field20;            /* 0x20  cleared on emit */
    float    vx;                 /* 0x24 */
    float    vy;                 /* 0x28  zero for every type except blood */
    float    vz;                 /* 0x2c */
} PARTICLE;

typedef struct PLAYERDEF {
    long        id;             /* 0x00  0..25; the same as the index */
    float       scale;          /* 0x04  multiplied by PlayerSize */
    float       posOffsetX;     /* 0x08  added or subtracted by facing */
    float       height;         /* 0x0c  added to Z in ArcadePosTo3dPos */
    float       renderOffsetX;  /* 0x10  glTranslatef x, times +/-2.15 */
    float       renderOffsetZ;  /* 0x14  glTranslatef z, times 0.65 */
    const char *lighting;       /* 0x18  "KANO" */
    const char *frameList;      /* 0x1c  "kanoframes.txt" */
    const char *bones;          /* 0x20  "KANO_STANDARD.bones" */
    const char *skin;           /* 0x24  "KANO_STANDARD.skin" */
    const char *skinAnim;       /* 0x28  "KANO_STANDARD.skinanim" */
    const char *texBase;        /* 0x2c  "KANO" */
    const char *scene;          /* 0x30  "KANO_STANDARD.scene" */
} PLAYERDEF;

typedef struct SOUNDENTRY {             /* 8 bytes: the walk advances by 8 */
    const char *name;                   /* 0x00 */
    long        id;                     /* 0x04, -1 when not loaded */
} SOUNDENTRY;

typedef struct TEXTURE {
    uint8_t  _pad00[0x40];
    unsigned name;               /* 0x40  the GL texture name */
    uint8_t  _pad44[0x0c];
    int      field50;            /* 0x50 */
} TEXTURE;

typedef struct TEXTURETOLOAD {
    const char *name;            /* 0x00  NULL ends the list */
    TEXTURE   **dest;            /* 0x04  where the handle goes */
} TEXTURETOLOAD;

typedef struct TOKEN {
    long type;                          /* 0x00  1..4, see below */
    union {
        long  word;                     /* 0x04  str  -- cases 1, 2 and 4 */
        short half;                     /* 0x04  strh -- case 3, low half only */
    } value;
    long value2;                        /* 0x08, only the 8-byte case uses it */
} TOKEN;

typedef struct TRAININGMOVE {
    const char *name;                   /* 0x00  NULL ends the category */
    const char *notation4;              /* 0x04  the 4-button layout */
    const char *notation5;              /* 0x08  the 5-button layout */
    const char *notation6;              /* 0x0c  the 6-button layout */
    long        pad10;                  /* 0x10 */
    /* 0x14 -- a pointer to the flag the move raises, or NULL. The table holds
     * 0x0014fb30 on the fatality row and 0x0014fb2c on the animality one, which
     * are `FatalityMessage` and `AnimalityMessage`; every other row is zero. */
    long       *messageFlag;            /* 0x14 */
} TRAININGMOVE;

typedef struct limeVECTOR3 { float x, y, z; } limeVECTOR3;


typedef struct GAMEFONT {
    uint8_t   _pad00[4];
    int       simple;            /* 0x04  stored INVERTED from the file flag */
    int       glyphHeight;       /* 0x08  header byte 2 -- ONE height for every
                                  *       glyph, which is why it is in the
                                  *       header and not in a per-glyph array */
    int       spacing;           /* 0x0c  added once per character by both
                                  *       width routines -- inter-character
                                  *       spacing, set from limeCreateFONT */
    int       fallbackAdvance;   /* 0x10  the constant 8 */
    /* A FLOAT. Both width routines read it with `vldr s15, [r4, #0x14]`, which
     * reinterprets the bits -- it does not convert an integer. An earlier
     * version of this header typed it `int` and the clean C cast it, which
     * gives the right answer only when the caller happened to pass a small
     * whole number. */
    float     field14;           /* 0x14  the scale applied at measure time */
    int16_t   numGlyphs;         /* 0x18 */
    uint8_t   _pad1a[2];
    /* The atlas rectangle of each glyph. limeDrawFONT settles all three by what
     * it divides them BY on the way to limeDrawSprite: atlasU and glyphWidth are
     * both normalised by +0x34, atlasV by +0x38. Two share a divisor, so two
     * share an axis. */
    int16_t  *atlasU;            /* 0x1c  x position in the atlas */
    int16_t  *atlasV;            /* 0x20  y position in the atlas */
    int16_t  *glyphWidth;        /* 0x24  per-glyph width, and the advance
                                  *       limeGetStringWidth accumulates */
    /* Optional per-glyph kerning, one SIGNED byte each, added to the width when
     * the pointer is non-null. limeGetStringWidth is the only reader:
     *     ldr     r3, [r4, #0x28]
     *     cmp     r3, #0
     *     ldrsbne r3, [r3, r0]
     *     addne   r8, r8, r3
     * Nothing in limeCreateFONT was seen to allocate it, so a font that does not
     * carry kerning leaves it null and every glyph keeps its plain width. */
    int8_t   *kerning;           /* 0x28 */
    int       defaultAdvance;    /* 0x2c  simple fonts only */
    uint8_t   _pad30[4];
    /* The atlas dimensions, and they are the OPPOSITE way round from an earlier
     * naming here. +0x34 divides the horizontal metrics and +0x38 the vertical,
     * which is what fixes them: the divisor names the axis. */
    float     atlasWidth;        /* 0x34 */
    float     atlasHeight;       /* 0x38 */
    /* Added to the width of a character that is NOT in the table, on top of
     * the fallback advance. Only the not-found branch reads it:
     *     ldr r3, [r4, #0x10]   ; the fallback
     *     ldr r2, [r4, #0x3c]   ; and this
     *     add r3, r3, r2
     * so a font can make unknown characters wider than the plain fallback
     * without touching the fallback itself. */
    int       extraUnknown;      /* 0x3c */
    uint8_t   _pad3c[12];
    uint8_t  *codes;             /* 0x48  one byte per glyph */
    int16_t  *codesW;            /* 0x4c  the same codes widened to 16 bits */
    TEXTURE  *texture0;          /* 0x50 */
    TEXTURE  *texture1;          /* 0x54 */
} GAMEFONT;

typedef struct {
    MOVESSECTION section[2];
    long         rows3;                 /* section 3 -- never displayed */
    const long  *moves5_3;
    const long  *moves6_3;
} MOVESLISTENTRY;

#endif
