/* Generated by tools/mkglobals.py -- do not hand-edit.
 *
 * The struct layouts the decompiled globals need, scraped from the .c
 * files that established them. Copying them by hand would let the two
 * drift, and the offsets are the part that was expensive to prove.
 */

#ifndef GAMECODE_GLOBALS_H
#define GAMECODE_GLOBALS_H

#include <stdint.h>

typedef struct ANIMATEDCHARACTER ANIMATEDCHARACTER;
typedef struct BARS BARS;
typedef struct BONESINFO BONESINFO;
typedef struct FRONTEND_CHARACTER FRONTEND_CHARACTER;
typedef struct LocaleManager LocaleManager;
typedef struct MESHSETINFO MESHSETINFO;
typedef struct Mk3Obj_t Mk3Obj_t;
typedef struct PLAYERDEF PLAYERDEF;
typedef struct SKININFO SKININFO;
typedef struct limeMATRIX44 limeMATRIX44;
typedef struct limeVECTOR2 limeVECTOR2;

#ifndef BIOS_PAGES
#define BIOS_PAGES 26
#endif
#ifndef CHARACTER_SLOTS
#define CHARACTER_SLOTS 26
#endif
#ifndef CS_COLS
#define CS_COLS 7
#endif
#ifndef CS_ROWS
#define CS_ROWS 4
#endif
#ifndef GAME_EVENT_SLOTS
#define GAME_EVENT_SLOTS 16
#endif
#ifndef GAME_EVENT_STRIDE
#define GAME_EVENT_STRIDE 0x64
#endif
#ifndef JOY_DIRECTIONS
#define JOY_DIRECTIONS 9
#endif
#ifndef PARTICLE_COUNT
#define PARTICLE_COUNT (PARTICLE_POOL / PARTICLE_STRIDE)
#endif
#ifndef PARTICLE_POOL
#define PARTICLE_POOL 0x6000u
#endif
#ifndef PARTICLE_STRIDE
#define PARTICLE_STRIDE 0x30u
#endif
#ifndef PEER_ROWS
#define PEER_ROWS 8
#endif
#ifndef PEER_STRIDE
#define PEER_STRIDE 0x40
#endif
#ifndef PRELOAD_STRIDE
#define PRELOAD_STRIDE 0x5f4
#endif
#ifndef WANTFRAMES_BYTES
#define WANTFRAMES_BYTES 0x1c4c
#endif

struct BUTTONNEW {
    long  style;                        /* 0x00, 0..8; anything else is a
                                         *       full-texture fallback */
    long  w;                            /* 0x04 */
    long  h;                            /* 0x08 */
    short thickness;                    /* 0x0c, for the red highlight */
    short pad;                          /* 0x0e */
    float pressed;                      /* 0x10, set to 1.0f on release */
};
typedef struct BUTTONNEW BUTTONNEW;

typedef struct CREDITSENTRY {
    long id;                            /* 0x00, -1 leaves the row blank */
    long scale10;                       /* 0x04 */
} CREDITSENTRY;

typedef struct CSOUNDENTRY {
    uint32_t field00;            /* 0x00 */
    uint32_t field04;            /* 0x04  what get_csound returns */
} CSOUNDENTRY;

typedef struct EDITVAR {
    long        pad;                    /* 0x00 */
    const char *label;                  /* 0x04 */
    void       *target;                 /* 0x08 */
    float       lower;                  /* 0x0c */
    float       step;                   /* 0x10 */
    long        type;                   /* 0x14, 0 = heading */
} EDITVAR;

typedef struct FEACHIEVEMENTDESCR {
    long id;                            /* 0x00  GameText id of the name */
    long descr;                         /* 0x04  GameText id of the description */
    long pad08;                         /* 0x08 */
    long timer;                         /* 0x0c */
} FEACHIEVEMENTDESCR;

typedef struct FOUNDTOKEN {
    long        type;                   /* 0x00  0 none, 1 's', 2 'd', 4 'f' */
    long        index;                  /* 0x04  0..7 from the digit, -1 if none */
    long        unknown;                /* 0x08 */
    const char *at;                     /* 0x0c  the unit the type char sits on */
} FOUNDTOKEN;

typedef struct GAMEEVENT {
    int32_t active;                     /* 0x00  the only field this file touches */
    uint8_t rest[GAME_EVENT_STRIDE - 4];
} GAMEEVENT;

typedef struct GAMEFONT {
    uint8_t   _pad00[0x0c];
    int       spacing;                  /* 0x0c */
    int       fallbackAdvance;          /* 0x10 */
    uint8_t   _pad14[4];
    int16_t   numGlyphs;                /* 0x18 */
    uint8_t   _pad1a[0x2e];
    uint8_t  *codes;                    /* 0x48  one byte per glyph */
    int16_t  *codesW;                   /* 0x4c  the same, widened */
} GAMEFONT;

typedef struct GAMESTATE {
    uint8_t _pad000[0x368];
    /* The two health BARS, and they are the health scaled by 1.66 -- see
     * ResetFightData, which writes 166/83/41 beside health 100/50/25 and
     * computes the survival one as `Health[0] * 166 / 100`. */
    long    healthBar1;                 /* 0x368 */
    long    healthBar2;                 /* 0x36c */
    uint8_t _pad370[0x44e - 0x370];
    int16_t field44e;                   /* 0x44e  ldrsh, normalised to 0 or 1 */
} GAMESTATE;

typedef struct KODE {
    long seq[6];                        /* 0x00 .. 0x14 */
    long unused;                        /* 0x18, never read by checkIfKode */
    long value;                         /* 0x1c */
} KODE;

typedef struct MKEVENT {
    signed char type;
    signed char player;
    signed char subtype;
    signed char pad;
    int32_t     param;
} MKEVENT;

typedef struct MKEVENTQUEUE {
    int32_t count;
    MKEVENT event[1];
} MKEVENTQUEUE;

typedef struct MKMOVE {
    long unused;                        /* 0x00 */
    long mask;                          /* 0x04  the bit pattern to match */
    long index;                         /* 0x08  into _VeteranMoves */
} MKMOVE;

typedef struct {
    long        rows;
    long        nameId;                 /* GameText base A */
    long        captionId;              /* GameText base B */
    const long *moves5;
    const long *moves6;
} MOVESSECTION;

typedef struct PARTICLE {
    float    field00;            /* 0x00  a size, four steps of PSize/4 */
    float    field04;            /* 0x04  set together with field08, same value */
    float    field08;            /* 0x08  the free marker InitParticles clears */
    int32_t  field0c;            /* 0x0c  the type AddParticles was called with */
    float    field10;            /* 0x10  x, passed straight through */
    float    field14;            /* 0x14  y + blood_zoff */
    float    field18;            /* 0x18  z + blood_yoff */
    uint8_t  _pad1c[4];          /* 0x1c  not touched by AddParticles */
    float    field20;            /* 0x20  cleared on emit */
    float    vx;                 /* 0x24 */
    float    vy;                 /* 0x28  zero for every type except blood */
    float    vz;                 /* 0x2c */
} PARTICLE;

typedef struct SOUNDENTRY {             /* 8 bytes: the walk advances by 8 */
    const char *name;                   /* 0x00 */
    long        id;                     /* 0x04, -1 when not loaded */
} SOUNDENTRY;

typedef struct TEXTURE {
    uint8_t  _pad00[0x40];
    unsigned name;               /* 0x40  the GL texture name */
    uint8_t  _pad44[0x0c];
    int      field50;            /* 0x50 */
} TEXTURE;

typedef struct TEXTURETOLOAD {
    const char *name;            /* 0x00  NULL ends the list */
    TEXTURE   **dest;            /* 0x04  where the handle goes */
} TEXTURETOLOAD;

typedef struct TOKEN {
    long type;                          /* 0x00  1..4, see below */
    union {
        long  word;                     /* 0x04  str  -- cases 1, 2 and 4 */
        short half;                     /* 0x04  strh -- case 3, low half only */
    } value;
    long value2;                        /* 0x08, only the 8-byte case uses it */
} TOKEN;

typedef struct TRAININGMOVE {
    const char *name;                   /* 0x00  NULL ends the category */
    const char *notation4;              /* 0x04  the 4-button layout */
    const char *notation5;              /* 0x08  the 5-button layout */
    const char *notation6;              /* 0x0c  the 6-button layout */
    long        pad10;                  /* 0x10 */
    long        pad14;                  /* 0x14 */
} TRAININGMOVE;

typedef struct limeVECTOR3 { float x, y, z; } limeVECTOR3;


typedef struct {
    MOVESSECTION section[2];
    long         rows3;                 /* section 3 -- never displayed */
    const long  *moves5_3;
    const long  *moves6_3;
} MOVESLISTENTRY;

#endif
