#!/usr/bin/env python3
"""level_info.py -- the arena names `_Level_Info` points at, from the user's binary.

    python tools/level_info.py <UMK3 binary> <out.c>

`_Level_Info` (0x0014e8d4, 16 records of 0xf4 bytes) is emitted by
tools/mkglobals.py as a byte array, because the decomp declares it `char[]`.
Some of its words are addresses: `+0x1c` and `+0x50` are the two background
scene file names GameInit_LoadABit hands to LIME_LoadScene (steps 27 and 28),
and `+0x74`..`+0xb0` are the sixteen layer-texture names. Copied as bytes they
are iOS addresses, and the first LIME_LoadScene of a fight read a string at
0x0014e2a0 of the host's address space.

They all point into one place: the anonymous strings the compiler put in
`__DATA,__data` straight after `_CurrentScene` (0x0014e29c, a 4-byte long) and
before `_Level_Info` -- 0x0014e2a0..0x0014e8d4. No symbol names that range, so
mkglobals.py never emitted it.

This writes that range as a byte array and a list of the Level_Info words that
point into it, and `umk3_relocate_level_info()`, which rewrites each of those
words as the host address of the same byte. A word is relocated when, and only
when, its value falls inside that range; every other word is a number (floats,
the BGEXTENTS words, flags) and is left alone. The relocated offsets are
printed so the classification can be audited.

The output holds game data: it belongs in the build directory, never in the
repository. 32-bit hosts only -- Level_Info's words are four bytes.
"""

import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import logic_tables  # noqa: E402  (load: thin or fat, armv7 slice)

LEVEL_INFO = "_Level_Info"
POOL_AFTER = "_CurrentScene"      # the 4-byte global the pool follows


def main(argv):
    if len(argv) != 3:
        raise SystemExit(__doc__.strip().splitlines()[2].strip())
    data, base, m = logic_tables.load(argv[1])

    syms = {}
    for name, n_type, n_sect, n_desc, n_value in m.symbols():
        if n_type & 0xe0 == 0 and n_type & 0x0e == 0x0e:   # N_SECT, not a stab
            syms.setdefault(name, n_value)
    info = syms[LEVEL_INFO]
    after = syms[POOL_AFTER]
    later = sorted(v for v in syms.values() if v > info)
    info_size = later[0] - info
    pool_lo, pool_hi = after + 4, info
    if any(pool_lo <= v < pool_hi for v in syms.values()):
        raise SystemExit("a symbol inside the string pool: the layout changed")

    sect = m.section_for_addr(info)
    if (sect.segname, sect.sectname) != ("__DATA", "__data"):
        raise SystemExit("%s is not in __DATA,__data" % LEVEL_INFO)

    def at(addr, n):
        s = m.section_for_addr(addr)
        o = base + s.offset + addr - s.addr
        return data[o:o + n]

    pool = at(pool_lo, pool_hi - pool_lo)
    relocs = []
    for off in range(0, info_size - 3, 4):
        w = struct.unpack_from("<I", at(info + off, 4))[0]
        if pool_lo <= w < pool_hi:
            relocs.append((off, w - pool_lo))
    if not relocs:
        raise SystemExit("no Level_Info word points into the pool")

    out = []
    out.append("/* Generated by tools/level_info.py from %s -- game data, do not commit. */"
               % os.path.basename(argv[1]))
    out.append("#include <stdint.h>\n")
    out.append("typedef char umk3_level_info_needs_32bit[sizeof(void *) == 4 ? 1 : -1];\n")
    out.append("extern char Level_Info[];  /* 0x%08x, %d bytes */\n" % (info, info_size))
    out.append("/* 0x%08x..0x%08x: the anonymous strings after %s */"
               % (pool_lo, pool_hi, POOL_AFTER[1:]))
    out.append("static char pool[%d] = {" % len(pool))
    for i in range(0, len(pool), 16):
        out.append("    " + ", ".join("0x%02x" % b for b in pool[i:i + 16]) + ",")
    out.append("};\n")
    out.append("static const uint16_t reloc_off[%d] = {" % len(relocs))
    for i in range(0, len(relocs), 8):
        out.append("    " + ", ".join("0x%03x" % o for o, _ in relocs[i:i + 8]) + ",")
    out.append("};")
    out.append("static const uint16_t reloc_pool[%d] = {" % len(relocs))
    for i in range(0, len(relocs), 8):
        out.append("    " + ", ".join("0x%03x" % p for _, p in relocs[i:i + 8]) + ",")
    out.append("};\n")
    out.append("void umk3_relocate_level_info(void)\n{")
    out.append("    unsigned i;\n")
    out.append("    for (i = 0; i < %d; i++)" % len(relocs))
    out.append("        *(uint32_t *)(Level_Info + reloc_off[i]) =")
    out.append("            (uint32_t)(uintptr_t)(pool + reloc_pool[i]);")
    out.append("}")
    with open(argv[2], "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")

    fields = sorted({o % 0xf4 for o, _ in relocs})
    print("level_info: %d words relocated into a %d-byte pool; record offsets %s"
          % (len(relocs), len(pool), " ".join("0x%02x" % o for o in fields)))


if __name__ == "__main__":
    main(sys.argv)
