#!/usr/bin/env python3
"""seq_data.py -- the special-move playback scripts, from the user's binary.

    python tools/seq_data.py <UMK3 binary> <out.c>

seq_lookup (0x000adb80) returns the address of a playback script: a stream
of 16-bit instructions (SET, CLEAR, HOLD, END, EMIT -- see
decomp/gamecode/logic/playback.c) that Playback_Update feeds to the fight as
joystick bits. The scripts sit in __TEXT,__const between 0x000de242 and the
end of that section, with no symbol naming them, and hold no pointers.

decomp/gamecode/logic/playback.c keeps seq_lookup's table as the binary's
addresses. This writes the bytes those addresses point at, and

    const unsigned char *umk3_seq_addr(unsigned long ios_address);

which returns the host address of the same byte -- so the table stays
exactly as walked out of the binary, and only the final pointer moves.

The output holds game data: it belongs in the build directory, never in the
repository.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import logic_tables  # noqa: E402  (load: thin or fat, armv7 slice)

SEQ_LO = 0x000de242       # the lowest address in seq_lookup's table


def main(argv):
    if len(argv) != 3:
        raise SystemExit(__doc__.strip().splitlines()[2].strip())
    data, base, m = logic_tables.load(argv[1])

    sect = m.section_for_addr(SEQ_LO)
    if (sect.segname, sect.sectname) != ("__TEXT", "__const"):
        raise SystemExit("0x%08x is not in __TEXT,__const: the layout changed"
                         % SEQ_LO)
    hi = sect.addr + sect.size
    off = base + sect.offset + SEQ_LO - sect.addr
    blob = data[off:off + hi - SEQ_LO]

    out = []
    out.append("/* Generated by tools/seq_data.py from %s -- game data, do not commit. */"
               % os.path.basename(argv[1]))
    out.append("#include <stddef.h>\n")
    out.append("/* 0x%08x..0x%08x, __TEXT,__const */" % (SEQ_LO, hi))
    out.append("static const unsigned short seq_words[%d] = {" % ((len(blob) + 1) // 2))
    if len(blob) % 2:
        blob += b"\0"
    words = [blob[i] | blob[i + 1] << 8 for i in range(0, len(blob), 2)]
    for i in range(0, len(words), 12):
        out.append("    " + ", ".join("0x%04x" % w for w in words[i:i + 12]) + ",")
    out.append("};\n")
    out.append("const unsigned char *umk3_seq_addr(unsigned long ios_address)\n{")
    out.append("    if (ios_address < 0x%08xul || ios_address >= 0x%08xul)" % (SEQ_LO, hi))
    out.append("        return NULL;")
    out.append("    return (const unsigned char *)seq_words + (ios_address - 0x%08xul);"
               % SEQ_LO)
    out.append("}")
    with open(argv[2], "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("seq_data: %d bytes of playback scripts" % len(blob))


if __name__ == "__main__":
    main(sys.argv)
