"""sounds.py -- recover the engine's sound-group table from the binary.

    python tools/sounds.py [path to res/audio]        print the groups
    python tools/sounds.py [path] --c                 emit it as C

`group_sound`, `ochar_sound`, `tsound_func` and `rsnd_func` all take a group
number and play one of its members. The group table is one of the 229 data
tables `docs/PROGRESS.md` records as uncounted, and this is the first of them
recovered.

## How it is stored, and how that was established

Not as an array of `const char *`. The first attempt looked for one and found
only Objective-C selector tables, which is itself the useful negative result:
**the names are stored inline**, as a run of NUL-terminated strings in
`__cstring` with a literal `end_of_list` ending each group. So a group number
is a COUNT of separators from the start of the run, and the reader walks it.

## Why the reading is trusted

Because it is checked against something it cannot control. Every name that is
not a separator has to be a real file in the user's own extracted
`res/audio` -- and 401 of them are, with the only failures in the first group,
which holds the `KODE_*` cheat strings and is adjacent data rather than part
of the table. A blob that were really something else would not survive that.

Pass the audio directory to run the check. Without it the groups still print,
but nothing has been verified and the output says so.

## What this does NOT establish

**The group NUMBERS here count from the start of the run, and the engine's may
not.** `group_sound` is in other.c and is not decompiled, so where it starts
counting -- and whether it skips anything -- is unknown. The numbering below is
therefore relative and the ADDRESSES are the thing to trust. Anything that
needs an absolute index has to wait for that function to be read.

The window was narrowed to the run itself after a first pass at 0x176000 swept
in the neighbouring `KODE_*` cheat strings, the debug-window labels and the
move-list text as a single enormous "group 0". They are adjacent data, not part
of the table, and including them shifted every index by one.
"""

import io
import os
import re
import sys

BASE = 0x1000                 # file offset = address - 0x1000
LO, HI = 0x177bf0, 0x17b400   # the run itself, not its neighbours


def groups(binary="work/UMK3.armv7"):
    """Every group, as (address of its first name, [names])."""
    b = io.open(binary, "rb").read()
    seq = []
    for m in re.finditer(rb"[\x20-\x7e]{2,40}\x00", b[LO:HI]):
        seq.append((LO + m.start() + BASE, m.group(0)[:-1].decode("ascii")))

    out, cur, first = [], [], None
    for a, s in seq:
        if s == "end_of_list":
            out.append((first, cur))
            cur, first = [], None
        else:
            if first is None:
                first = a
            cur.append(s)
    if cur:
        out.append((first, cur))
    return out


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    as_c = "--c" in sys.argv
    audio = args[0] if args else None

    have = set()
    if audio and os.path.isdir(audio):
        have = set(os.path.splitext(f)[0].lower() for f in os.listdir(audio))

    g = groups()
    named = [(a, n) for a, n in g if n]

    if as_c:
        print("/* Generated by tools/sounds.py -- do not edit by hand. */")
        print("static const char *const SND[][12] = {")
        for i, (a, names) in enumerate(g):
            row = ", ".join('"%s"' % n for n in names[:11])
            print("    { %s%sNULL },   /* %2d  %08x */"
                  % (row, ", " if row else "", i, a or 0))
        print("};")
        return

    if have:
        ok = sum(1 for _, n in named for x in n if x.lower() in have)
        bad = sum(1 for _, n in named for x in n if x.lower() not in have)
        print("checked against %d files in %s" % (len(have), audio))
        print("%d groups; %d names ARE a .wav, %d are not\n" % (len(g), ok, bad))
    else:
        print("%d groups. NOT CHECKED -- pass res/audio to verify.\n" % len(g))

    for i, (a, names) in enumerate(g):
        if not names:
            continue
        mark = ("".join("." if n.lower() in have else "?" for n in names)
                if have else "")
        print("  %3d @%08x %s %s"
              % (i, a or 0, ("[%s]" % mark) if mark else "", " ".join(names)))


if __name__ == "__main__":
    main()
