if(NOT DEFINED HTML_FILE OR NOT EXISTS "${HTML_FILE}")
    message(FATAL_ERROR "Emscripten HTML output was not found: ${HTML_FILE}")
endif()
if(NOT DEFINED JS_VERSION)
    message(FATAL_ERROR "JS_VERSION is required to cache-bust the browser script.")
endif()

file(READ "${HTML_FILE}" html)
set(old_tag "src=\"umk3-browser-v6.js\"")
set(new_tag "src=\"umk3-browser-v6.js?v=${JS_VERSION}\"")
string(FIND "${html}" "${old_tag}" tag_position)
if(tag_position EQUAL -1)
    message(FATAL_ERROR "Could not find the generated Emscripten script tag.")
endif()
string(REPLACE "${old_tag}" "${new_tag}" html "${html}")
file(WRITE "${HTML_FILE}" "${html}")
